import { AuditRun } from './audit-run.entity';
import { AuditTask } from './audit-task.entity';

// Builds the "Branded report" the user's spec calls for: "create a Branded
// report ... report will be generated and view on customer panel." The
// customer panel itself isn't built yet (not yet started per the migration
// plan), so for now this HTML is served directly by GET
// /api/v1/customers/:customerId/audits/:runId/report and is meant to be
// embedded/iframed once that panel exists.
export function buildBrandedReportHtml(
  run: AuditRun,
  tasks: AuditTask[],
  customerName: string,
): string {
  const byLayer = groupByLayer(tasks);
  const automated = tasks.filter((t) => t.isAutomated);
  const withFindings = tasks.filter((t) => t.status === 'completed' && t.finding);

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Openink Hub — Complete Website Audit — ${escapeHtml(customerName)}</title>
${styleBlock()}
</head>
<body>
  <header class="brand-header">
    <div class="brand-mark">Openink Hub</div>
    <h1>Complete Website Audit</h1>
    <p class="meta">${escapeHtml(customerName)} &middot; ${escapeHtml(run.website ?? '')} &middot; ${formatDate(run.completedAt ?? run.createdAt)}</p>
  </header>
  ${summaryBlock(run, tasks, automated, withFindings)}
  ${layerSectionsBlock(byLayer)}
  ${appendixBlock(tasks)}
  <footer class="brand-footer">Generated by the Openink Hub AI-SEO Engine &middot; Layer 69 — Complete Website Audit</footer>
</body>
</html>`;
}

function groupByLayer(tasks: AuditTask[]): Map<number, AuditTask[]> {
  const map = new Map<number, AuditTask[]>();
  for (const task of tasks) {
    if (!task.finding) continue;
    for (const layer of task.layerNumbers) {
      if (!map.has(layer)) map.set(layer, []);
      map.get(layer)!.push(task);
    }
  }
  return new Map([...map.entries()].sort((a, b) => a[0] - b[0]));
}

function summaryBlock(run: AuditRun, tasks: AuditTask[], automated: AuditTask[], withFindings: AuditTask[]): string {
  const stat = (label: string, value: string | number) =>
    `<div class="stat"><div class="stat-value">${value}</div><div class="stat-label">${escapeHtml(label)}</div></div>`;
  return `<section class="summary">
    ${stat('Skills assessed', tasks.length)}
    ${stat('Live technical checks', automated.length)}
    ${stat('Findings generated', withFindings.length)}
    ${stat('Layers mapped', new Set(tasks.flatMap((t) => t.layerNumbers)).size)}
    ${stat('Status', run.status)}
  </section>`;
}

function layerSectionsBlock(byLayer: Map<number, AuditTask[]>): string {
  if (byLayer.size === 0) {
    return '<section class="layers"><h2>Findings by Layer</h2><p class="empty">No layer-mapped findings yet.</p></section>';
  }
  const sections = [...byLayer.entries()]
    .map(
      ([layer, tasks]) => `<div class="layer-card">
        <h3>Layer ${layer}</h3>
        <ul>
          ${tasks.map((t) => `<li><strong>${escapeHtml(t.skill)}</strong> (${escapeHtml(t.plugin)}): ${escapeHtml(t.finding ?? '')}${t.suggestion ? ` <em>&mdash; ${escapeHtml(t.suggestion)}</em>` : ''}</li>`).join('')}
        </ul>
      </div>`,
    )
    .join('');
  return `<section class="layers"><h2>Findings by Layer</h2>${sections}</section>`;
}

function appendixBlock(tasks: AuditTask[]): string {
  const rows = tasks
    .map(
      (t) => `<tr>
        <td>${escapeHtml(t.group)}</td>
        <td>${escapeHtml(t.plugin)}:${escapeHtml(t.skill)}</td>
        <td>${escapeHtml(t.implementationType)}</td>
        <td>${escapeHtml(t.actionType)}</td>
        <td>${escapeHtml(t.layerNumbers.join(', ') || '—')}</td>
        <td>${escapeHtml(t.status)}${t.isAutomated ? '' : ' (pending data source)'}</td>
        <td>${escapeHtml(truncate(t.finding ?? '', 140))}</td>
      </tr>`,
    )
    .join('');
  return `<section class="appendix">
    <h2>All 140 Skills — Task Detail</h2>
    <table>
      <thead><tr><th>Group</th><th>Skill</th><th>Type</th><th>Action</th><th>Layer(s)</th><th>Status</th><th>Finding</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
  </section>`;
}

function styleBlock(): string {
  return `<style>
    :root { --ink:#1a1a2e; --muted:#5b5b6e; --accent:#2563eb; --surface:#ffffff; --line:#e2e2ea; }
    body { font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin:0; background:#f6f6f9; color:var(--ink); }
    .brand-header { background:var(--ink); color:#fff; padding:32px 24px; }
    .brand-mark { font-weight:700; letter-spacing:0.08em; text-transform:uppercase; font-size:13px; opacity:0.75; }
    .brand-header h1 { margin:6px 0 4px; font-size:28px; }
    .meta { margin:0; opacity:0.8; font-size:14px; }
    section { padding:24px; max-width:1100px; margin:0 auto; }
    .summary { display:flex; gap:16px; flex-wrap:wrap; }
    .stat { background:var(--surface); border:1px solid var(--line); border-radius:10px; padding:16px 20px; min-width:140px; }
    .stat-value { font-size:26px; font-weight:700; color:var(--accent); }
    .stat-label { font-size:12px; color:var(--muted); text-transform:uppercase; letter-spacing:0.04em; }
    .layer-card { background:var(--surface); border:1px solid var(--line); border-radius:10px; padding:16px 20px; margin-bottom:16px; }
    .layer-card h3 { margin-top:0; color:var(--accent); }
    table { width:100%; border-collapse:collapse; font-size:13px; background:var(--surface); }
    th, td { border-bottom:1px solid var(--line); padding:8px 10px; text-align:left; vertical-align:top; }
    th { background:#fafafc; }
    .brand-footer { text-align:center; padding:24px; color:var(--muted); font-size:12px; }
    .empty { color:var(--muted); }
  </style>`;
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c] as string);
}

function truncate(s: string, max: number): string {
  return s.length > max ? `${s.slice(0, max - 1)}…` : s;
}

function formatDate(d: Date): string {
  return new Date(d).toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' });
}
